# This is a basic workflow to help you get started with Actions

name: test-neo-regress

# Controls when the workflow will run
on: 
  push:
    branches:
      - 'main'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #schedule:
  #  - cron: '14 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: rm git repo
        run: cd ~/test_action; rm -rf neo-server; rm -rf neo-test;
      - name: clone neo-server
        run: cd ~/test_action; git clone git@github.com:machbase/neo-server.git;
      - name: clone neo-test
        run: cd ~/test_action; git clone git@github.com:machbase/neo-test.git;
      - name: build machbase-neo
        run: cd ~/test_action/neo-server; make machbase-neo;
      - name: run test
        run: cd ~/test_action/neo-test/testsuite; ntf startup.tc shutdown.tc;
      - name: check run
        run: cd ~/test_action/neo-test/testsuite; cat summary.txt | grep RUN | grep COUNT | gawk '{print $4}' > run_count.out;
      - name: check pass
        run: cd ~/test_action/neo-test/testsuite; cat summary.txt | grep PASS | grep COUNT | gawk '{print $4}' > pass_count.out;
      - name: diff
        run: cd ~/test_action/neo-test/testsuite; diff run_count.out pass_count.out;
        
